version: '3.7'
services:
  app:
    container_name: miniature-calendar-api
    image: nahuelrodriguez/miniature-calendar-api:latest
    build:
      context: .
    environment:
      SPRING_REDIS_HOST: redis
    ports:
      - "80:8080"
    depends_on:
      - redis
    restart: always

  redis:
    container_name: redis
    image: redis:6.2.6
    ports:
      - "6379:6379"
