apiVersion: v1
kind: Service
metadata:
  labels:
    app: min-cal-api
  name: min-cal-svc
spec:
  ports:
    - port: 4433
      protocol: TCP
      targetPort: 4433
      nodePort: 30003
  type: NodePort
  selector:
    app: min-cal-api
